# Generated by Django 2.2.5 on 2019-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dogtag_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_type', models.TextField()),
                ('dog_name', models.TextField()),
            ],
        ),
    ]
