# Generated by Django 2.2.5 on 2019-11-15 19:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_newdog'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdog',
            name='dog_birthday',
            field=models.DateField(default=datetime.datetime(2019, 11, 15, 19, 28, 33, 609942, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
